### ISSUE TITLE
Readme Visual Studio (IDE) Guide

### ISSUE THREAD

**Issue by amki** [mumble-voip/mumble-releng-experimental#8]
I've tried following https://github.com/mumble-voip/mumble-releng-vcpkg#visual-studio-ide and everything worked out fine but when I try to launch my self-compiled mumble.exe it tells me:

Mumble Launcher Error -4
Unable to find expected entry point ('MumbleMain') in mumble_app.dll.

Any idea why this might be happening?

**Comment by ghost** [comment]
If the code compiled without error then this should probably be an issue here:

https://github.com/mumble-voip/mumble

Try executing it from the folder as well as in Visual Studio. If the same error results then please open an issue for the Mumble repo.

**Comment by amki** [comment]
Technically the result was Build All failed but the only error is the "The system was unable to find the specified registry key or value." that I was told to ignore so I guess that is a successful compilation?

It doesn't generate the api-ms* files that it still seems to depend on and which are inside a normal Mumble install which looks liked it skipped something?

It did go through all 733 cmake tasks though.

**Comment by amki** [comment]
Update: This only happens for "Configuration type:" "Debug". If I set the Configuration type to "Release" I can launch it without a problem (Result is still Build all failed)

I guess it should be mentioned in the guide that "Configuration type" has to be set to Release, for me Debug was the default.

**Comment by ghost** [comment]
In the Option Define table is `-DCMAKE_BUILD_TYPE=` and setting it to Release should produce a configuration that defaults to Release. To the best of my knowledge, Debug may not work for Windows or produces large binaries according to @davidebeatrici but that may be updated.

**Comment by amki** [comment]
It's not described in the Visual Studio (IDE) part of the README so I left it to it's default value. Visual Studio has a dropdown Selector called "configuration type" which says "This corresponds to CMAKE_BUILD_TYPE".

I guess it would be nice to add that step before step 4 "As CMake command argument add"

The Debug mumble_app.dll is indeed >100MB while the Release one is ~58MB for me but the main problem is that it doesn't start with the aforementioned error.

**Comment by ghost** [comment]
I will discuss the status of Debug with @davidebeatrici and revise the document as needed. Thanks for letting us know.

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issue!

The debug build failing to start is fixed in mumble-voip/mumble#4429.

The "Build all failed" error is due to the following:
```
[DEBUG:VsDevCmd.bat] calling "ext\perf_tools.bat"
C:\mumble\out\build\x64\EXEC : error : The system was unable to find the specified registry key or value.
```

It happens during the 32 bit overlay library/loader build, but it doesn't abort it.

The error doesn't appear outside of Visual Studio, but it's probably just because `vcvars` is not ran in debug mode.

We have to investigate.

> It doesn't generate the api-ms* files that it still seems to depend on and which are inside a normal Mumble install which looks liked it skipped something?

Those are UCRT DLLs, normally provided by Microsoft. We ship both CRT and UCRT libraries in 1.3.x, but it's considered bad practice, in fact the 1.4.x installer doesn't provide them.

**Comment by amki** [comment]
I can confirm that as of https://github.com/mumble-voip/mumble/commit/43975f3a8712d1fbf440b96cd9afbd78f496c8a3 the debug build now also works, thus the original problem is fixed.

Thanks for the quick fix! :)

**Comment by davidebeatrici** [comment]
No problem! :)

@ZeroAbility Should we perhaps move the build guide to the main repository?

**Comment by ghost** [comment]
I would suggest, yes. Especially if there are alternate dependency methods besides vcpkg.
